### ISSUE TITLE
Thread blocked error on 1000 RPM repository

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#116]
When running `Rpm.batchUpdate()` for repository with >=1000 RPM packages, it throws an exception:
```
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.5/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base@11.0.5/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base@11.0.5/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base@11.0.5/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base@11.0.5/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
	at java.base@11.0.5/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base@11.0.5/java.nio.channels.Channels.writeFully(Channels.java:97)
	at java.base@11.0.5/java.nio.channels.Channels$1.write(Channels.java:172)
	at java.base@11.0.5/java.io.OutputStream.write(OutputStream.java:122)
	at java.base@11.0.5/java.nio.channels.Channels$1.write(Channels.java:152)
	at java.xml@11.0.5/com.sun.xml.internal.stream.writers.UTF8OutputStreamWriter.write(UTF8OutputStreamWriter.java:92)
	at java.xml@11.0.5/com.sun.xml.internal.stream.writers.UTF8OutputStreamWriter.write(UTF8OutputStreamWriter.java:133)
	at java.xml@11.0.5/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeXMLContent(XMLStreamWriterImpl.java:1543)
	at java.xml@11.0.5/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeXMLContent(XMLStreamWriterImpl.java:1461)
	at java.xml@11.0.5/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeCharacters(XMLStreamWriterImpl.java:701)
	at app//com.artipie.rpm.meta.XmlFilelists$Package.files(XmlFilelists.java:187)
	at app//com.artipie.rpm.pkg.FilelistsOutput.accept(FilelistsOutput.java:87)
	at app//com.artipie.rpm.pkg.MetadataFile.accept(MetadataFile.java:77)
	at app//com.artipie.rpm.pkg.PackageOutput$Multiple.accept(PackageOutput.java:141)
	at app//com.artipie.rpm.Repository.accept(Repository.java:106)
	at app//com.artipie.rpm.pkg.FilePackage.save(FilePackage.java:76)
	at app//com.artipie.rpm.Repository.update(Repository.java:79)
	at app//com.artipie.rpm.Rpm$$Lambda$359/0x0000000800280c40.apply(Unknown Source)
	at app//io.reactivex.internal.operators.observable.ObservableReduceSeedSingle$ReduceSeedObserver.onNext(ObservableReduceSeedSingle.java:80)
	at app//io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.drainLoop(ObservableFlatMapSingle.java:263)
	at app//io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.innerSuccess(ObservableFlatMapSingle.java:178)
	at app//io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver$InnerObserver.onSuccess(ObservableFlatMapSingle.java:284)
	at app//io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at app//io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at app//io.reactivex.Single.subscribe(Single.java:3603)
	at app//io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:69)
	at app//io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at app//io.reactivex.subjects.CompletableSubject.onComplete(CompletableSubject.java:139)
	at app//hu.akarnokd.rxjava2.interop.CompletableInterop.lambda$fromFuture$3(CompletableInterop.java:77)
	at app//hu.akarnokd.rxjava2.interop.CompletableInterop$$Lambda$336/0x000000080024e040.accept(Unknown Source)
	at java.base@11.0.5/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base@11.0.5/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base@11.0.5/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base@11.0.5/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at app//hu.akarnokd.rxjava2.interop.CompletableInterop.lambda$null$0(CompletableInterop.java:47)
	at app//hu.akarnokd.rxjava2.interop.CompletableInterop$$Lambda$327/0x0000000800248440.run(Unknown Source)
	at app//io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
	at app//io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at app//io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at app//io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
	at app//io.reactivex.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onSuccess(CompletableFromSingle.java:51)
	at app//io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at app//io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onComplete(SingleFlatMapPublisher.java:117)
	at app//io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at app//io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber.otherComplete(FlowableMergeWithCompletable.java:120)
	at app//io.reactivex.internal.operators.flowable.FlowableMergeWithCompletable$MergeWithSubscriber$OtherObserver.onComplete(FlowableMergeWithCompletable.java:147)
	at app//io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
	at app//com.artipie.asto.fs.RxFile.lambda$null$0(RxFile.java:89)
	at app//com.artipie.asto.fs.RxFile$$Lambda$524/0x00000008002e4c40.handle(Unknown Source)
	at app//io.vertx.reactivex.core.Future$2.handle(Future.java:161)
	at app//io.vertx.reactivex.core.Future$2.handle(Future.java:158)
	at app//io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107)
	at app//io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152)
	at app//io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:159)
	at app//io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:120)
	at app//io.vertx.reactivex.core.Promise.complete(Promise.java:104)
	at app//com.artipie.asto.fs.RxFile$$Lambda$535/0x00000008002e8040.run(Unknown Source)
	at app//io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
	at app//io.vertx.reactivex.impl.AsyncResultCompletable.lambda$subscribeActual$0(AsyncResultCompletable.java:48)
	at app//io.vertx.reactivex.impl.AsyncResultCompletable$$Lambda$543/0x00000008002e9440.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$437/0x00000008002ae440.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at app//io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at app//io.vertx.core.impl.EventLoopContext$$Lambda$445/0x00000008002b0040.run(Unknown Source)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.5/java.lang.Thread.run(Thread.java:834)

```

**Comment by 0crat** [comment]
The job [#116](https://github.com/artipie/rpm-adapter/issues/116) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/19533bd4-d582-41e9-9e8e-0b35de991bc8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.3`

**Comment by g4s8** [comment]
Fixed and released

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
