### ISSUE TITLE
Couldn't close underlying outputs with ClassCastException

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#164]
The error happened in `XmlFile.alterTag` with `ClassCastException`, see the stacktrace:

```
Caused by: java.io.IOException: Couldn't close underlying outputs
        at com.artipie.rpm.pkg.PackageOutput$Multiple.close(PackageOutput.java:157)
        at com.artipie.rpm.Repository.close(Repository.java:91)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
        at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        ... 3 more
        Suppressed: java.io.IOException: Failed to alter file
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:130)
                at com.artipie.rpm.meta.XmlPrimary.close(XmlPrimary.java:106)
                at com.artipie.rpm.pkg.PrimaryOutput.close(PrimaryOutput.java:122)
                at com.artipie.rpm.pkg.MetadataFile.close(MetadataFile.java:83)
                at com.artipie.rpm.pkg.PackageOutput$Multiple.close(PackageOutput.java:151)
                ... 16 more
        Caused by: javax.xml.transform.TransformerException: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:118)
                ... 20 more
        Caused by: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.handleEndElement(StAXEvent2SAX.java:341)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.bridge(StAXEvent2SAX.java:198)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.parse(StAXEvent2SAX.java:115)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:673)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
                ... 22 more
        Suppressed: java.io.IOException: Failed to alter file
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:130)
                at com.artipie.rpm.meta.XmlPackagesFile.close(XmlPackagesFile.java:99)
                at com.artipie.rpm.meta.XmlOthers.close(XmlOthers.java:98)
                at com.artipie.rpm.pkg.OthersOutput.close(OthersOutput.java:98)
                at com.artipie.rpm.pkg.MetadataFile.close(MetadataFile.java:83)
                at com.artipie.rpm.pkg.PackageOutput$Multiple.close(PackageOutput.java:151)
                ... 16 more
        Caused by: javax.xml.transform.TransformerException: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:118)
                ... 21 more
        Caused by: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.handleEndElement(StAXEvent2SAX.java:341)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.bridge(StAXEvent2SAX.java:198)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.parse(StAXEvent2SAX.java:115)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:673)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
                ... 23 more
        Suppressed: java.io.IOException: Failed to alter file
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:130)
                at com.artipie.rpm.meta.XmlPackagesFile.close(XmlPackagesFile.java:99)
                at com.artipie.rpm.meta.XmlFilelists.close(XmlFilelists.java:102)
                at com.artipie.rpm.pkg.FilelistsOutput.close(FilelistsOutput.java:101)
                at com.artipie.rpm.pkg.MetadataFile.close(MetadataFile.java:83)
                at com.artipie.rpm.pkg.PackageOutput$Multiple.close(PackageOutput.java:151)
                ... 16 more
        Caused by: javax.xml.transform.TransformerException: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
                at com.artipie.rpm.meta.XmlFile.alterTag(XmlFile.java:118)
                ... 21 more
        Caused by: java.lang.ClassCastException: org.codehaus.stax2.ri.evt.NamespaceEventImpl cannot be cast to java.lang.String
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.handleEndElement(StAXEvent2SAX.java:341)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.bridge(StAXEvent2SAX.java:198)
                at com.sun.org.apache.xalan.internal.xsltc.trax.StAXEvent2SAX.parse(StAXEvent2SAX.java:115)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:673)
                at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
                ... 23 more
```

**Comment by 0crat** [comment]
The job [#164](https://github.com/artipie/rpm-adapter/issues/164) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/08ffd828-9bdf-4682-9ef1-9b10170da2d0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 is this bug stable? I cannot reproduce it with jdk1.8.0_171 on macos. I'm not sure yet, but it looks like https://bugs.openjdk.java.net/browse/JDK-8198355

**Comment by g4s8** [comment]
@olenagerasimova it's not stable, and I can't reproduce it too. This error I received from rpm adapter users.

**Comment by olenagerasimova** [comment]
@g4s8 on what jdk is rpm adapter running there?

**Comment by g4s8** [comment]
@olenagerasimova they are using 1.8

**Comment by olenagerasimova** [comment]
@g4s8 is it possible to find out minor version and what jdk is it - open or oracle?

**Comment by g4s8** [comment]
> @g4s8 is it possible to find out minor version and what jdk is it - open or oracle?

@olenagerasimova they are using custom JDK implementation based on OpenJDK 1.8

**Comment by olenagerasimova** [comment]
@g4s8 I have not got any lack reproducing this error with different jdk8 (that's just a part https://github.com/olenagerasimova/rpm-adapter/runs/653959934). The most straightforward solution here - rewrite entire method with different approach. We can either get rid of `StAX` and use xml streams only or simply replace tag value re-writing file line by line with buffered reader/writer. Second approach will be faster, but it's less reliable.

**Comment by g4s8** [comment]
> @g4s8 I have not got any lack reproducing this error with different jdk8 (that's just a part https://github.com/olenagerasimova/rpm-adapter/runs/653959934). The most straightforward solution here - rewrite entire method with different approach. We can either get rid of `StAX` and use xml streams only or simply replace tag value re-writing file line by line with buffered reader/writer. Second approach will be faster, but it's less reliable.

@olenagerasimova ok, let's try with second option.

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.1`

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@g4s8 were there any info from our colleague? Can we say that bug is fixed and close the issue?

**Comment by g4s8** [comment]
@olenagerasimova yes, it was fixed, thanks.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
