### ISSUE TITLE
Benchmarks fail to run with error

### ISSUE THREAD

**Issue by milkysoft** [artipie/rpm-adapter#387]
```
ls -l
total 251408
-rw-rw-r-- 1 zuoqin zuoqin 182280842 Apr 21 08:21 bundle1000.tar.gz
-rw-rw-r-- 1 zuoqin zuoqin  75119223 Apr 21 08:21 bundle100.tar.gz
-rw-rw-r-- 1 zuoqin zuoqin      1079 Apr 20 12:33 LICENSE.txt
-rw-rw-r-- 1 zuoqin zuoqin     15472 Apr 20 12:40 pom.xml
-rw-rw-r-- 1 zuoqin zuoqin      6194 Apr 20 12:33 README.md
drwxrwxr-x 4 zuoqin zuoqin      4096 Apr 20 12:33 src
drwxrwxr-x 9 zuoqin zuoqin      4096 Apr 20 12:41 target
```

`env BENCH_DIR=${PWD} java -Xmx9048m -cp "targetenchmarks.jar:target/classes/*:target/dependency/*" org.openjdk.jmh.Main RpmBench`

```
# Run progress: 0.00% complete, ETA 00:20:50
# Fork: 1 of 5
# Warmup Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<failure>

java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/repo-618645420643333442/primary.xml.gz
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at com.artipie.rpm.benchmarks.RpmBench.run(RpmBench.java:101)
	at com.artipie.rpm.benchmarks.jmh_generated.RpmBench_run_jmhTest.run_avgt_jmhStub(RpmBench_run_jmhTest.java:306)
	at com.artipie.rpm.benchmarks.jmh_generated.RpmBench_run_jmhTest.run_AverageTime(RpmBench_run_jmhTest.java:229)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:470)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/repo-618645420643333442/primary.xml.gz
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.reactivex.internal.functions.Functions$FutureAction.run(Functions.java:161)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.Completable.subscribe(Completable.java:2383)
	at hu.akarnokd.rxjava2.interop.CompletableInterop.lambda$await$1(CompletableInterop.java:47)
	at io.reactivex.Completable.to(Completable.java:2597)
	at com.artipie.rpm.benchmarks.RpmBench.run(RpmBench.java:100)
	... 14 more
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/repo-618645420643333442/primary.xml.gz
	at com.artipie.asto.fs.FileStorage.lambda$move$13(FileStorage.java:267)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	... 3 more
Caused by: java.nio.file.NoSuchFileException: /tmp/repo-618645420643333442/primary.xml.gz
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:468)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at com.artipie.asto.fs.FileStorage.lambda$move$13(FileStorage.java:265)
	... 5 more
```

**Comment by olenagerasimova** [comment]
@milkysoft hm, cannot reproduce the error. Benchmark requires rpm repo in the test directory, have you unpacked any of the bundles?

**Comment by olenagerasimova** [comment]
cannot reproduce
