### ISSUE TITLE
com.artipie.rpm.RpmTest#addsSingleRpm is broken

### ISSUE THREAD

**Issue by dgarus** [artipie/rpm-adapter#55]
The test com.artipie.rpm.RpmTest#addsSingleRpm is broken with error
```
java.io.FileNotFoundException: /etc/hosts (Too many open files)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at io.netty.resolver.HostsFileParser.parse(HostsFileParser.java:132)
	at io.netty.resolver.HostsFileParser.parseSilently(HostsFileParser.java:89)
	at io.netty.resolver.HostsFileParser.parseSilently(HostsFileParser.java:76)
	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:123)
	at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:39)
	at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:75)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:169)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:27)
	at io.vertx.core.Vertx.vertx(Vertx.java:75)
	at io.vertx.reactivex.core.Vertx.vertx(Vertx.java:118)
	at com.artipie.asto.fs.RxFile.<init>(RxFile.java:64)
	at com.artipie.rpm.Repomd.lambda$performUpdate$17(Repomd.java:197)
```

MacOS.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@dgarus please provide more details: OS, Java version, etc. I can't reproduce it locally and CI build is OK.

**Comment by dgarus** [comment]
@g4s8 
OS:	macOS 10.15.4 (19E266)
Java: 13.0.2 or 11.0.6

I think I don't have '/etc/hosts' file.

**Comment by olenagerasimova** [comment]
`RpmTest` was rewritten and does not have such method anymore. Moreover it works on both win and linux as we can see from github actions.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#55` is not assigned, can't get performer
